FROM node:18-alpine

WORKDIR /usr/src/app

# Copiar package.json
COPY package*.json ./

# Instalar dependencias
RUN npm install --omit=dev

# Copiar código
COPY . .

# Exponer puerto
EXPOSE 5000

ENV NODE_ENV=production PORT=5000

CMD ["node", "server.js"]
